# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bunkhouse/events/envelope.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bunkhouse/events/envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bunkhouse.events import task_pb2 as bunkhouse_dot_events_dot_task__pb2
from bunkhouse.events import step_pb2 as bunkhouse_dot_events_dot_step__pb2
from bunkhouse.events import workflow_run_pb2 as bunkhouse_dot_events_dot_workflow__run__pb2
from bunkhouse.events import github_pb2 as bunkhouse_dot_events_dot_github__pb2
from bunkhouse.events import deployment_pb2 as bunkhouse_dot_events_dot_deployment__pb2
from bunkhouse.events import workflow_def_pb2 as bunkhouse_dot_events_dot_workflow__def__pb2
from bunkhouse.events import repo_pb2 as bunkhouse_dot_events_dot_repo__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x62unkhouse/events/envelope.proto\x12\x10\x62unkhouse.events\x1a\x1b\x62unkhouse/events/task.proto\x1a\x1b\x62unkhouse/events/step.proto\x1a#bunkhouse/events/workflow_run.proto\x1a\x1d\x62unkhouse/events/github.proto\x1a!bunkhouse/events/deployment.proto\x1a#bunkhouse/events/workflow_def.proto\x1a\x1b\x62unkhouse/events/repo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x03\n\x0e\x42unkhouseEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12/\n\x0boccurred_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06source\x18\x03 \x01(\t\x12+\n\x04task\x18\x04 \x01(\x0b\x32\x1b.bunkhouse.events.TaskEventH\x00\x12+\n\x04step\x18\x05 \x01(\x0b\x32\x1b.bunkhouse.events.StepEventH\x00\x12:\n\x0cworkflow_run\x18\x06 \x01(\x0b\x32\".bunkhouse.events.WorkflowRunEventH\x00\x12/\n\x06github\x18\x07 \x01(\x0b\x32\x1d.bunkhouse.events.GitHubEventH\x00\x12\x37\n\ndeployment\x18\x08 \x01(\x0b\x32!.bunkhouse.events.DeploymentEventH\x00\x12\x41\n\x0cworkflow_def\x18\t \x01(\x0b\x32).bunkhouse.events.WorkflowDefinitionEventH\x00\x12+\n\x04repo\x18\n \x01(\x0b\x32\x1b.bunkhouse.events.RepoEventH\x00\x12\x16\n\x0eschema_version\x18\x64 \x01(\rB\t\n\x07payloadB7Z5github.com/bunkhouse/protobuf/gen/go/bunkhouse/eventsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bunkhouse.events.envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/bunkhouse/protobuf/gen/go/bunkhouse/events'
  _globals['_BUNKHOUSEEVENT']._serialized_start=314
  _globals['_BUNKHOUSEEVENT']._serialized_end=816
# @@protoc_insertion_point(module_scope)
