# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bunkhouse/events/repo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bunkhouse/events/repo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x62unkhouse/events/repo.proto\x12\x10\x62unkhouse.events\x1a\x1cgoogle/protobuf/struct.proto\"Z\n\tRepoEvent\x12\x0c\n\x04repo\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x65\x66\x61ult_branch\x18\x02 \x01(\t\x12\'\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructB7Z5github.com/bunkhouse/protobuf/gen/go/bunkhouse/eventsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bunkhouse.events.repo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/bunkhouse/protobuf/gen/go/bunkhouse/events'
  _globals['_REPOEVENT']._serialized_start=79
  _globals['_REPOEVENT']._serialized_end=169
# @@protoc_insertion_point(module_scope)
